/*
* generated by Xtext
*/
package org.xtext.example.mydsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final RuleCall cBodyParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		/// *
		// * SO FAR
		// * 
		// * LEX.PPNUMBER     [OK]
		// * LEX.NAME         [OK]
		// * LEX.KEY          [OK]
		// * LEX.OPERATORS    [OK]
		// * Lex.Token        [OK]
		// *
		// * / Model:
		//	Body;
		public ParserRule getRule() { return rule; }

		//Body
		public RuleCall getBodyParserRuleCall() { return cBodyParserRuleCall; }
	}

	public class BodyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Body");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBodyAction_0 = (Action)cGroup.eContents().get(0);
		private final RuleCall cPreprocessing_fileParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cFuncoesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFuncoesFunctionDeclarationParserRuleCall_2_0 = (RuleCall)cFuncoesAssignment_2.eContents().get(0);
		
		//Body:
		//	{Body} preprocessing_file funcoes+=FunctionDeclaration*;
		public ParserRule getRule() { return rule; }

		//{Body} preprocessing_file funcoes+=FunctionDeclaration*
		public Group getGroup() { return cGroup; }

		//{Body}
		public Action getBodyAction_0() { return cBodyAction_0; }

		//preprocessing_file
		public RuleCall getPreprocessing_fileParserRuleCall_1() { return cPreprocessing_fileParserRuleCall_1; }

		//funcoes+=FunctionDeclaration*
		public Assignment getFuncoesAssignment_2() { return cFuncoesAssignment_2; }

		//FunctionDeclaration
		public RuleCall getFuncoesFunctionDeclarationParserRuleCall_2_0() { return cFuncoesFunctionDeclarationParserRuleCall_2_0; }
	}

	public class Elif_groupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elif_group");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cElifKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cConstant_expressionParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final RuleCall cGroupParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//// INCLUDE, DEFINES
		//elif_group:
		//	"#elif" constant_expression group?;
		public ParserRule getRule() { return rule; }

		//"#elif" constant_expression group?
		public Group getGroup() { return cGroup; }

		//"#elif"
		public Keyword getElifKeyword_0() { return cElifKeyword_0; }

		//constant_expression
		public RuleCall getConstant_expressionParserRuleCall_1() { return cConstant_expressionParserRuleCall_1; }

		//group?
		public RuleCall getGroupParserRuleCall_2() { return cGroupParserRuleCall_2; }
	}

	public class Constant_expressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "constant_expression");
		private final RuleCall cConditional_expressionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//constant_expression:
		//	conditional_expression;
		public ParserRule getRule() { return rule; }

		//conditional_expression
		public RuleCall getConditional_expressionParserRuleCall() { return cConditional_expressionParserRuleCall; }
	}

	public class Conditional_expressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "conditional_expression");
		private final Keyword cTODOKeyword = (Keyword)rule.eContents().get(1);
		
		//conditional_expression:
		//	"TODO";
		public ParserRule getRule() { return rule; }

		//"TODO"
		public Keyword getTODOKeyword() { return cTODOKeyword; }
	}

	public class Preprocessing_fileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "preprocessing_file");
		private final RuleCall cGroupParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//preprocessing_file:
		//	group?;
		public ParserRule getRule() { return rule; }

		//group?
		public RuleCall getGroupParserRuleCall() { return cGroupParserRuleCall; }
	}

	public class Preprocessing_tokenElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "preprocessing_token");
		private final RuleCall cHEADER_NAMETerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		////	PPNUMBER|
		////	CHARLITERAL|
		//preprocessing_token:
		//	HEADER_NAME;
		public ParserRule getRule() { return rule; }

		//HEADER_NAME
		public RuleCall getHEADER_NAMETerminalRuleCall() { return cHEADER_NAMETerminalRuleCall; }
	}

	public class Else_groupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "else_group");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cElseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cGroupParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//else_group:
		//	"#else" group?;
		public ParserRule getRule() { return rule; }

		//"#else" group?
		public Group getGroup() { return cGroup; }

		//"#else"
		public Keyword getElseKeyword_0() { return cElseKeyword_0; }

		//group?
		public RuleCall getGroupParserRuleCall_1() { return cGroupParserRuleCall_1; }
	}

	public class Endif_lineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "endif_line");
		private final Keyword cEndifKeyword = (Keyword)rule.eContents().get(1);
		
		//endif_line:
		//	"#endif";
		public ParserRule getRule() { return rule; }

		//"#endif"
		public Keyword getEndifKeyword() { return cEndifKeyword; }
	}

	public class Control_lineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "control_line");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cIncludeKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cPp_tokensParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cDefineKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final RuleCall cReplacement_listParserRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cDefineKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final RuleCall cLparenParserRuleCall_2_2 = (RuleCall)cGroup_2.eContents().get(2);
		private final RuleCall cIDTerminalRuleCall_2_3 = (RuleCall)cGroup_2.eContents().get(3);
		private final Keyword cRightParenthesisKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final RuleCall cReplacement_listParserRuleCall_2_5 = (RuleCall)cGroup_2.eContents().get(5);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Keyword cUndefKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Keyword cLineKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final RuleCall cPp_tokensParserRuleCall_4_1 = (RuleCall)cGroup_4.eContents().get(1);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Keyword cErrorKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final RuleCall cPp_tokensParserRuleCall_5_1 = (RuleCall)cGroup_5.eContents().get(1);
		private final Group cGroup_6 = (Group)cAlternatives.eContents().get(6);
		private final Keyword cPragmaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final RuleCall cPp_tokensParserRuleCall_6_1 = (RuleCall)cGroup_6.eContents().get(1);
		private final Keyword cNumberSignKeyword_7 = (Keyword)cAlternatives.eContents().get(7);
		
		//control_line:
		//	"#include" pp_tokens | "#define" ID replacement_list | "#define" ID lparen ID? ")" replacement_list | "#undef" ID |
		//	"#line" pp_tokens | "#error" pp_tokens? | "#pragma" pp_tokens? | "#";
		public ParserRule getRule() { return rule; }

		//"#include" pp_tokens | "#define" ID replacement_list | "#define" ID lparen ID? ")" replacement_list | "#undef" ID |
		//"#line" pp_tokens | "#error" pp_tokens? | "#pragma" pp_tokens? | "#"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"#include" pp_tokens
		public Group getGroup_0() { return cGroup_0; }

		//"#include"
		public Keyword getIncludeKeyword_0_0() { return cIncludeKeyword_0_0; }

		//pp_tokens
		public RuleCall getPp_tokensParserRuleCall_0_1() { return cPp_tokensParserRuleCall_0_1; }

		//"#define" ID replacement_list
		public Group getGroup_1() { return cGroup_1; }

		//"#define"
		public Keyword getDefineKeyword_1_0() { return cDefineKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }

		//replacement_list
		public RuleCall getReplacement_listParserRuleCall_1_2() { return cReplacement_listParserRuleCall_1_2; }

		//"#define" ID lparen ID? ")" replacement_list
		public Group getGroup_2() { return cGroup_2; }

		//"#define"
		public Keyword getDefineKeyword_2_0() { return cDefineKeyword_2_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_2_1() { return cIDTerminalRuleCall_2_1; }

		//lparen
		public RuleCall getLparenParserRuleCall_2_2() { return cLparenParserRuleCall_2_2; }

		//ID?
		public RuleCall getIDTerminalRuleCall_2_3() { return cIDTerminalRuleCall_2_3; }

		//")"
		public Keyword getRightParenthesisKeyword_2_4() { return cRightParenthesisKeyword_2_4; }

		//replacement_list
		public RuleCall getReplacement_listParserRuleCall_2_5() { return cReplacement_listParserRuleCall_2_5; }

		//"#undef" ID
		public Group getGroup_3() { return cGroup_3; }

		//"#undef"
		public Keyword getUndefKeyword_3_0() { return cUndefKeyword_3_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_3_1() { return cIDTerminalRuleCall_3_1; }

		//"#line" pp_tokens
		public Group getGroup_4() { return cGroup_4; }

		//"#line"
		public Keyword getLineKeyword_4_0() { return cLineKeyword_4_0; }

		//pp_tokens
		public RuleCall getPp_tokensParserRuleCall_4_1() { return cPp_tokensParserRuleCall_4_1; }

		//"#error" pp_tokens?
		public Group getGroup_5() { return cGroup_5; }

		//"#error"
		public Keyword getErrorKeyword_5_0() { return cErrorKeyword_5_0; }

		//pp_tokens?
		public RuleCall getPp_tokensParserRuleCall_5_1() { return cPp_tokensParserRuleCall_5_1; }

		//"#pragma" pp_tokens?
		public Group getGroup_6() { return cGroup_6; }

		//"#pragma"
		public Keyword getPragmaKeyword_6_0() { return cPragmaKeyword_6_0; }

		//pp_tokens?
		public RuleCall getPp_tokensParserRuleCall_6_1() { return cPp_tokensParserRuleCall_6_1; }

		//"#"
		public Keyword getNumberSignKeyword_7() { return cNumberSignKeyword_7; }
	}

	public class LparenElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lparen");
		private final Keyword cLeftParenthesisKeyword = (Keyword)rule.eContents().get(1);
		
		//lparen:
		//	"(";
		public ParserRule getRule() { return rule; }

		//"("
		public Keyword getLeftParenthesisKeyword() { return cLeftParenthesisKeyword; }
	}

	public class Replacement_listElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "replacement_list");
		private final RuleCall cPp_tokensParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//replacement_list:
		//	pp_tokens?;
		public ParserRule getRule() { return rule; }

		//pp_tokens?
		public RuleCall getPp_tokensParserRuleCall() { return cPp_tokensParserRuleCall; }
	}

	public class Pp_tokensElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pp_tokens");
		private final RuleCall cPreprocessing_tokenParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//pp_tokens:
		//	preprocessing_token+;
		public ParserRule getRule() { return rule; }

		//preprocessing_token+
		public RuleCall getPreprocessing_tokenParserRuleCall() { return cPreprocessing_tokenParserRuleCall; }
	}

	public class GroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "group");
		private final RuleCall cGroup_partParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//group:
		//	group_part+;
		public ParserRule getRule() { return rule; }

		//group_part+
		public RuleCall getGroup_partParserRuleCall() { return cGroup_partParserRuleCall; }
	}

	public class Group_partElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "group_part");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIf_actionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cControl_lineParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//group_part:
		//	if_action | control_line;
		public ParserRule getRule() { return rule; }

		//if_action | control_line
		public Alternatives getAlternatives() { return cAlternatives; }

		//if_action
		public RuleCall getIf_actionParserRuleCall_0() { return cIf_actionParserRuleCall_0; }

		//control_line
		public RuleCall getControl_lineParserRuleCall_1() { return cControl_lineParserRuleCall_1; }
	}

	public class If_actionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "if_action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIf_groupParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cElif_groupsParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final RuleCall cElse_groupParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final RuleCall cEndif_lineParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//if_action:
		//	if_group elif_groups? else_group? endif_line;
		public ParserRule getRule() { return rule; }

		//if_group elif_groups? else_group? endif_line
		public Group getGroup() { return cGroup; }

		//if_group
		public RuleCall getIf_groupParserRuleCall_0() { return cIf_groupParserRuleCall_0; }

		//elif_groups?
		public RuleCall getElif_groupsParserRuleCall_1() { return cElif_groupsParserRuleCall_1; }

		//else_group?
		public RuleCall getElse_groupParserRuleCall_2() { return cElse_groupParserRuleCall_2; }

		//endif_line
		public RuleCall getEndif_lineParserRuleCall_3() { return cEndif_lineParserRuleCall_3; }
	}

	public class If_groupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "if_group");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cIfKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cConstant_expressionParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final RuleCall cGroupParserRuleCall_0_2 = (RuleCall)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cIfdefKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final RuleCall cGroupParserRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cIfndefKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final RuleCall cGroupParserRuleCall_2_2 = (RuleCall)cGroup_2.eContents().get(2);
		
		//if_group:
		//	"#if" constant_expression group? | "#ifdef" ID group? | "#ifndef" ID group?;
		public ParserRule getRule() { return rule; }

		//"#if" constant_expression group? | "#ifdef" ID group? | "#ifndef" ID group?
		public Alternatives getAlternatives() { return cAlternatives; }

		//"#if" constant_expression group?
		public Group getGroup_0() { return cGroup_0; }

		//"#if"
		public Keyword getIfKeyword_0_0() { return cIfKeyword_0_0; }

		//constant_expression
		public RuleCall getConstant_expressionParserRuleCall_0_1() { return cConstant_expressionParserRuleCall_0_1; }

		//group?
		public RuleCall getGroupParserRuleCall_0_2() { return cGroupParserRuleCall_0_2; }

		//"#ifdef" ID group?
		public Group getGroup_1() { return cGroup_1; }

		//"#ifdef"
		public Keyword getIfdefKeyword_1_0() { return cIfdefKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }

		//group?
		public RuleCall getGroupParserRuleCall_1_2() { return cGroupParserRuleCall_1_2; }

		//"#ifndef" ID group?
		public Group getGroup_2() { return cGroup_2; }

		//"#ifndef"
		public Keyword getIfndefKeyword_2_0() { return cIfndefKeyword_2_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_2_1() { return cIDTerminalRuleCall_2_1; }

		//group?
		public RuleCall getGroupParserRuleCall_2_2() { return cGroupParserRuleCall_2_2; }
	}

	public class Elif_groupsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "elif_groups");
		private final RuleCall cElif_groupParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//elif_groups:
		//	elif_group+;
		public ParserRule getRule() { return rule; }

		//elif_group+
		public RuleCall getElif_groupParserRuleCall() { return cElif_groupParserRuleCall; }
	}

	public class FunctionDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFunctionDeclarationAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeTypeParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cParamsAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cParamsParameterParserRuleCall_4_0_0 = (RuleCall)cParamsAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cParamsAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cParamsParameterParserRuleCall_4_1_1_0 = (RuleCall)cParamsAssignment_4_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cEscopoAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cEscopoStatementParserRuleCall_7_0 = (RuleCall)cEscopoAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//// FUNCTION
		//FunctionDeclaration:
		//	{FunctionDeclaration} type=Type name=ID "(" (params+=Parameter ("," params+=Parameter)*)? ")" "{" escopo=statement?
		//	"}";
		public ParserRule getRule() { return rule; }

		//{FunctionDeclaration} type=Type name=ID "(" (params+=Parameter ("," params+=Parameter)*)? ")" "{" escopo=statement? "}"
		public Group getGroup() { return cGroup; }

		//{FunctionDeclaration}
		public Action getFunctionDeclarationAction_0() { return cFunctionDeclarationAction_0; }

		//type=Type
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }

		//Type
		public RuleCall getTypeTypeParserRuleCall_1_0() { return cTypeTypeParserRuleCall_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }

		//(params+=Parameter ("," params+=Parameter)*)?
		public Group getGroup_4() { return cGroup_4; }

		//params+=Parameter
		public Assignment getParamsAssignment_4_0() { return cParamsAssignment_4_0; }

		//Parameter
		public RuleCall getParamsParameterParserRuleCall_4_0_0() { return cParamsParameterParserRuleCall_4_0_0; }

		//("," params+=Parameter)*
		public Group getGroup_4_1() { return cGroup_4_1; }

		//","
		public Keyword getCommaKeyword_4_1_0() { return cCommaKeyword_4_1_0; }

		//params+=Parameter
		public Assignment getParamsAssignment_4_1_1() { return cParamsAssignment_4_1_1; }

		//Parameter
		public RuleCall getParamsParameterParserRuleCall_4_1_1_0() { return cParamsParameterParserRuleCall_4_1_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }

		//escopo=statement?
		public Assignment getEscopoAssignment_7() { return cEscopoAssignment_7; }

		//statement
		public RuleCall getEscopoStatementParserRuleCall_7_0() { return cEscopoStatementParserRuleCall_7_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParameterAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeTypeParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Parameter:
		//	{Parameter} type=Type name=ID;
		public ParserRule getRule() { return rule; }

		//{Parameter} type=Type name=ID
		public Group getGroup() { return cGroup; }

		//{Parameter}
		public Action getParameterAction_0() { return cParameterAction_0; }

		//type=Type
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }

		//Type
		public RuleCall getTypeTypeParserRuleCall_1_0() { return cTypeTypeParserRuleCall_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
	}

	public class VarDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VarDecl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVarDeclAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeTypeParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//VarDecl:
		//	{VarDecl} type=Type name=ID;
		public ParserRule getRule() { return rule; }

		//{VarDecl} type=Type name=ID
		public Group getGroup() { return cGroup; }

		//{VarDecl}
		public Action getVarDeclAction_0() { return cVarDeclAction_0; }

		//type=Type
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }

		//Type
		public RuleCall getTypeTypeParserRuleCall_1_0() { return cTypeTypeParserRuleCall_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
	}

	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cStsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStsSimple_type_specifierParserRuleCall_1_0 = (RuleCall)cStsAssignment_1.eContents().get(0);
		
		//Type:
		//	{Type} sts=simple_type_specifier;
		public ParserRule getRule() { return rule; }

		//{Type} sts=simple_type_specifier
		public Group getGroup() { return cGroup; }

		//{Type}
		public Action getTypeAction_0() { return cTypeAction_0; }

		//sts=simple_type_specifier
		public Assignment getStsAssignment_1() { return cStsAssignment_1; }

		//simple_type_specifier
		public RuleCall getStsSimple_type_specifierParserRuleCall_1_0() { return cStsSimple_type_specifierParserRuleCall_1_0; }
	}

	public class Simple_type_specifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "simple_type_specifier");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cIntTypeAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final Keyword cNameIntKeyword_0_1_0 = (Keyword)cNameAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cBoolTypeAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Keyword cNameBoolKeyword_1_1_0 = (Keyword)cNameAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cUnknownTypeAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Assignment cNameAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_2_1_0 = (RuleCall)cNameAssignment_2_1.eContents().get(0);
		
		//simple_type_specifier:
		//	{IntType} name="int" | {BoolType} name="bool" | {UnknownType} name=ID;
		public ParserRule getRule() { return rule; }

		//{IntType} name="int" | {BoolType} name="bool" | {UnknownType} name=ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//{IntType} name="int"
		public Group getGroup_0() { return cGroup_0; }

		//{IntType}
		public Action getIntTypeAction_0_0() { return cIntTypeAction_0_0; }

		//name="int"
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }

		//"int"
		public Keyword getNameIntKeyword_0_1_0() { return cNameIntKeyword_0_1_0; }

		//{BoolType} name="bool"
		public Group getGroup_1() { return cGroup_1; }

		//{BoolType}
		public Action getBoolTypeAction_1_0() { return cBoolTypeAction_1_0; }

		//name="bool"
		public Assignment getNameAssignment_1_1() { return cNameAssignment_1_1; }

		//"bool"
		public Keyword getNameBoolKeyword_1_1_0() { return cNameBoolKeyword_1_1_0; }

		//{UnknownType} name=ID
		public Group getGroup_2() { return cGroup_2; }

		//{UnknownType}
		public Action getUnknownTypeAction_2_0() { return cUnknownTypeAction_2_0; }

		//name=ID
		public Assignment getNameAssignment_2_1() { return cNameAssignment_2_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_1_0() { return cNameIDTerminalRuleCall_2_1_0; }
	}

	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "statement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStatementAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cVariavelAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVariavelDeclaration_statementParserRuleCall_1_0 = (RuleCall)cVariavelAssignment_1.eContents().get(0);
		
		////// A.5
		////	selection_statement
		//statement: //	expression_statement|
		////	compound_statement|
		////	jump_statement|
		//	{statement} variavel=declaration_statement;
		public ParserRule getRule() { return rule; }

		////	expression_statement|
		////	compound_statement|
		////	jump_statement|
		//{statement} variavel=declaration_statement
		public Group getGroup() { return cGroup; }

		////	expression_statement|
		////	compound_statement|
		////	jump_statement|
		//{statement}
		public Action getStatementAction_0() { return cStatementAction_0; }

		//variavel=declaration_statement
		public Assignment getVariavelAssignment_1() { return cVariavelAssignment_1; }

		//declaration_statement
		public RuleCall getVariavelDeclaration_statementParserRuleCall_1_0() { return cVariavelDeclaration_statementParserRuleCall_1_0; }
	}

	public class Simple_declarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "simple_declaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVariavelAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cVariavelVarDeclParserRuleCall_0_0 = (RuleCall)cVariavelAssignment_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		////iteration_statement:
		////	'while (' condition ')' statement|
		////	'do' statement 'while ('expression ');'|
		////	'for ( 'for_init_statement condition? ';' expression? ')' statement;
		////
		////for_init_statement:
		////	expression_statement|simple_declaration;
		////
		//simple_declaration:
		//	variavel=VarDecl ";";
		public ParserRule getRule() { return rule; }

		//variavel=VarDecl ";"
		public Group getGroup() { return cGroup; }

		//variavel=VarDecl
		public Assignment getVariavelAssignment_0() { return cVariavelAssignment_0; }

		//VarDecl
		public RuleCall getVariavelVarDeclParserRuleCall_0_0() { return cVariavelVarDeclParserRuleCall_0_0; }

		//";"
		public Keyword getSemicolonKeyword_1() { return cSemicolonKeyword_1; }
	}

	public class Declaration_statementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "declaration_statement");
		private final Assignment cVariaveisAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cVariaveisBlock_declarationParserRuleCall_0 = (RuleCall)cVariaveisAssignment.eContents().get(0);
		
		////expression_statement:
		////	expression?
		////;
		////compound_statement:
		////	'{' statement_seq? '}';
		////	
		////statement_seq:
		////	(statement)+;
		////selection_statement:
		////	'if (' condition ')' statement |
		////	'if (' condition ')' statement |
		////	'switch (' condition ')' statement;
		////
		////
		////// TODO(condition')
		////condition:
		////	expression
		////;
		////jump_statement:
		////	'break;'|
		////	'continue;'|
		////	'return' expression?';'|
		////	'goto' ID';'
		////;
		//declaration_statement:
		//	variaveis+=block_declaration+;
		public ParserRule getRule() { return rule; }

		//variaveis+=block_declaration+
		public Assignment getVariaveisAssignment() { return cVariaveisAssignment; }

		//block_declaration
		public RuleCall getVariaveisBlock_declarationParserRuleCall_0() { return cVariaveisBlock_declarationParserRuleCall_0; }
	}

	public class Block_declarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "block_declaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBlock_declarationAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cVariavelAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVariavelSimple_declarationParserRuleCall_1_0 = (RuleCall)cVariavelAssignment_1.eContents().get(0);
		
		////
		////// TODO
		/// * 	
		//conditional_expression:
		////	logical_or_expression |
		//	logical_or_expression ('?' expression ':' assignment_expression)?;
		//
		//logical_or_expression:
		//	logical_and_expression ('||' logical_and_expression )*;
		//
		//logical_and_expression:
		//	inclusive_or_expression ('&&' inclusive_or_expression)*;
		//
		//inclusive_or_expression:
		//	exclusive_or_expression ('|' exclusive_or_expression)*;
		//
		//exclusive_or_expression:
		//	and_expression ('^' and_expression)*;
		//
		//and_expression:
		//	equality_expression ('&' equality_expression)*;
		//
		//equality_expression:
		//	relational_expression (('==' | '!=') relational_expression)*;
		//
		//relational_expression:
		//	shift_expression (('<' | '>' | '<=' | '>=') shift_expression)*;
		//
		//shift_expression:
		//	additive_expression (('<<' | '>>') additive_expression)*;
		//
		//additive_expression:
		//	multiplicative_expression (SIGN multiplicative_expression)*;
		//
		//multiplicative_expression:
		//	pm_expression (('*' | '/' | '%') pm_expression)*;
		//
		//pm_expression:
		//	cast_expression (('.*' | '->*') cast_expression)*;
		//
		//cast_expression:
		//	('(' ID ')')* unary_expression;
		//	//TODO replace ID with type_id, I guess
		//
		//unary_expression:
		//	('sizeof')* postfix_expression |
		//	('sizeof')* ('++' | '--' | unary_operator ) cast_expression |
		//	'sizeof' '(' ID ')' |//TODO replace ID with type_id
		//	('sizeof')* new_expression |
		//	('sizeof')* delete_expression;
		//
		//postfix_expression:
		//	primary_expression ('[' expression ']' |
		//						'(' expression_list? ')' |
		//						'.' 'template'? (ID) | //TODO replace ID with id_expression
		//						'->' 'template'? (ID) | //TODO replace ID with id_expression
		//						'++' |
		//						'--')*;
		//
		//primary_expression:
		//	'==primary==';
		//
		//pseudo_destructor_name:
		//	'::'? nested_name_specifier? type_name '::' '~' type_name |
		//	'::'? nested_name_specifier => 'template' template_id '::' '~' type_name;
		//
		//nested_name_specifier:
		//	class_or_namespace_name '::' nested_name_specifier?;
		////	class_or_namespace_name '::' => 'template' nested_name_specifier;
		//	
		//
		//class_or_namespace_name:
		//	class_name | namespace_name;
		//
		//class_name:
		//	ID | template_id;
		//
		//namespace_name:
		//	'==namespace==';
		//
		//type_name:
		//	'==type_name==';
		//
		//template_id:
		//	ID '<' template_argument_list? '>' 'class';
		//
		//template_argument_list:
		//	template_argument (',' template_argument)*;
		//
		//template_argument:
		//	assignment_expression |
		//	id_expression;
		//
		//id_expression:
		//	unqualified_id |
		//	qualified_id;
		//
		//unqualified_id:
		//	ID |
		//	operator_function_id |
		//	conversion_function_id |
		//	'~' class_name |
		//	template_id;
		//
		//operator_function_id:
		//	'operator' operator;
		//
		//operator:
		//	'new' | 'delete' | 'new[]' | 'delete[]' | '+' | '-' | '*' | '/' | '%' | '^' | '&' | '|' | '~' | '!' | '=' | '<' | '>' |
		//	'+=' | '-=' | '*=' | '/=' | '%=' | '^=' | '&=' | '|=' | '<<' | '>>' | '<<=' | '>>=' | '==' | '!=' | '<=' | '>=' | '&&' |
		//	'||' | '++' | '--' | ',' | '->*' | '->' | '()' | '[]';
		//
		//conversion_function_id:
		//	'operator' conversion_type_id;
		//
		//conversion_type_id:
		//	type_specifier_seq conversion_declarator?;
		//
		//conversion_declarator:
		//	'==conversion==';
		//
		//type_specifier_seq:
		//	type_specifier+;
		//
		//type_specifier:
		//	'==type_specifier==';
		//
		//qualified_id:
		//	'==qualified==';
		//
		//new_expression:
		//	'==new==';
		//
		//delete_expression:
		//	'==delete==';
		//
		//unary_operator:
		//	('*' | '&' | '+' | '-' | '!' | '~');
		//
		//expression_list:
		//	assignment_expression (',' assignment_expression)*;
		//
		//expression:
		//	'==expression==';
		//
		//assignment_expression:
		//	'==assignment==';
		//
		// * / block_declaration:
		//	{block_declaration} variavel=simple_declaration;
		public ParserRule getRule() { return rule; }

		//{block_declaration} variavel=simple_declaration
		public Group getGroup() { return cGroup; }

		//{block_declaration}
		public Action getBlock_declarationAction_0() { return cBlock_declarationAction_0; }

		//variavel=simple_declaration
		public Assignment getVariavelAssignment_1() { return cVariavelAssignment_1; }

		//simple_declaration
		public RuleCall getVariavelSimple_declarationParserRuleCall_1_0() { return cVariavelSimple_declarationParserRuleCall_1_0; }
	}
	
	
	private ModelElements pModel;
	private BodyElements pBody;
	private Elif_groupElements pElif_group;
	private Constant_expressionElements pConstant_expression;
	private Conditional_expressionElements pConditional_expression;
	private Preprocessing_fileElements pPreprocessing_file;
	private TerminalRule tHEADER_NAME;
	private Preprocessing_tokenElements pPreprocessing_token;
	private Else_groupElements pElse_group;
	private Endif_lineElements pEndif_line;
	private Control_lineElements pControl_line;
	private LparenElements pLparen;
	private Replacement_listElements pReplacement_list;
	private Pp_tokensElements pPp_tokens;
	private GroupElements pGroup;
	private Group_partElements pGroup_part;
	private If_actionElements pIf_action;
	private If_groupElements pIf_group;
	private Elif_groupsElements pElif_groups;
	private FunctionDeclarationElements pFunctionDeclaration;
	private ParameterElements pParameter;
	private VarDeclElements pVarDecl;
	private TypeElements pType;
	private Simple_type_specifierElements pSimple_type_specifier;
	private StatementElements pStatement;
	private Simple_declarationElements pSimple_declaration;
	private Declaration_statementElements pDeclaration_statement;
	private Block_declarationElements pBlock_declaration;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	/// *
	// * SO FAR
	// * 
	// * LEX.PPNUMBER     [OK]
	// * LEX.NAME         [OK]
	// * LEX.KEY          [OK]
	// * LEX.OPERATORS    [OK]
	// * Lex.Token        [OK]
	// *
	// * / Model:
	//	Body;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Body:
	//	{Body} preprocessing_file funcoes+=FunctionDeclaration*;
	public BodyElements getBodyAccess() {
		return (pBody != null) ? pBody : (pBody = new BodyElements());
	}
	
	public ParserRule getBodyRule() {
		return getBodyAccess().getRule();
	}

	//// INCLUDE, DEFINES
	//elif_group:
	//	"#elif" constant_expression group?;
	public Elif_groupElements getElif_groupAccess() {
		return (pElif_group != null) ? pElif_group : (pElif_group = new Elif_groupElements());
	}
	
	public ParserRule getElif_groupRule() {
		return getElif_groupAccess().getRule();
	}

	//constant_expression:
	//	conditional_expression;
	public Constant_expressionElements getConstant_expressionAccess() {
		return (pConstant_expression != null) ? pConstant_expression : (pConstant_expression = new Constant_expressionElements());
	}
	
	public ParserRule getConstant_expressionRule() {
		return getConstant_expressionAccess().getRule();
	}

	//conditional_expression:
	//	"TODO";
	public Conditional_expressionElements getConditional_expressionAccess() {
		return (pConditional_expression != null) ? pConditional_expression : (pConditional_expression = new Conditional_expressionElements());
	}
	
	public ParserRule getConditional_expressionRule() {
		return getConditional_expressionAccess().getRule();
	}

	//preprocessing_file:
	//	group?;
	public Preprocessing_fileElements getPreprocessing_fileAccess() {
		return (pPreprocessing_file != null) ? pPreprocessing_file : (pPreprocessing_file = new Preprocessing_fileElements());
	}
	
	public ParserRule getPreprocessing_fileRule() {
		return getPreprocessing_fileAccess().getRule();
	}

	//terminal HEADER_NAME:
	//	"<" (ID | ".") ">" | "\"" (ID | ".") "\"";
	public TerminalRule getHEADER_NAMERule() {
		return (tHEADER_NAME != null) ? tHEADER_NAME : (tHEADER_NAME = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "HEADER_NAME"));
	} 

	////	PPNUMBER|
	////	CHARLITERAL|
	//preprocessing_token:
	//	HEADER_NAME;
	public Preprocessing_tokenElements getPreprocessing_tokenAccess() {
		return (pPreprocessing_token != null) ? pPreprocessing_token : (pPreprocessing_token = new Preprocessing_tokenElements());
	}
	
	public ParserRule getPreprocessing_tokenRule() {
		return getPreprocessing_tokenAccess().getRule();
	}

	//else_group:
	//	"#else" group?;
	public Else_groupElements getElse_groupAccess() {
		return (pElse_group != null) ? pElse_group : (pElse_group = new Else_groupElements());
	}
	
	public ParserRule getElse_groupRule() {
		return getElse_groupAccess().getRule();
	}

	//endif_line:
	//	"#endif";
	public Endif_lineElements getEndif_lineAccess() {
		return (pEndif_line != null) ? pEndif_line : (pEndif_line = new Endif_lineElements());
	}
	
	public ParserRule getEndif_lineRule() {
		return getEndif_lineAccess().getRule();
	}

	//control_line:
	//	"#include" pp_tokens | "#define" ID replacement_list | "#define" ID lparen ID? ")" replacement_list | "#undef" ID |
	//	"#line" pp_tokens | "#error" pp_tokens? | "#pragma" pp_tokens? | "#";
	public Control_lineElements getControl_lineAccess() {
		return (pControl_line != null) ? pControl_line : (pControl_line = new Control_lineElements());
	}
	
	public ParserRule getControl_lineRule() {
		return getControl_lineAccess().getRule();
	}

	//lparen:
	//	"(";
	public LparenElements getLparenAccess() {
		return (pLparen != null) ? pLparen : (pLparen = new LparenElements());
	}
	
	public ParserRule getLparenRule() {
		return getLparenAccess().getRule();
	}

	//replacement_list:
	//	pp_tokens?;
	public Replacement_listElements getReplacement_listAccess() {
		return (pReplacement_list != null) ? pReplacement_list : (pReplacement_list = new Replacement_listElements());
	}
	
	public ParserRule getReplacement_listRule() {
		return getReplacement_listAccess().getRule();
	}

	//pp_tokens:
	//	preprocessing_token+;
	public Pp_tokensElements getPp_tokensAccess() {
		return (pPp_tokens != null) ? pPp_tokens : (pPp_tokens = new Pp_tokensElements());
	}
	
	public ParserRule getPp_tokensRule() {
		return getPp_tokensAccess().getRule();
	}

	//group:
	//	group_part+;
	public GroupElements getGroupAccess() {
		return (pGroup != null) ? pGroup : (pGroup = new GroupElements());
	}
	
	public ParserRule getGroupRule() {
		return getGroupAccess().getRule();
	}

	//group_part:
	//	if_action | control_line;
	public Group_partElements getGroup_partAccess() {
		return (pGroup_part != null) ? pGroup_part : (pGroup_part = new Group_partElements());
	}
	
	public ParserRule getGroup_partRule() {
		return getGroup_partAccess().getRule();
	}

	//if_action:
	//	if_group elif_groups? else_group? endif_line;
	public If_actionElements getIf_actionAccess() {
		return (pIf_action != null) ? pIf_action : (pIf_action = new If_actionElements());
	}
	
	public ParserRule getIf_actionRule() {
		return getIf_actionAccess().getRule();
	}

	//if_group:
	//	"#if" constant_expression group? | "#ifdef" ID group? | "#ifndef" ID group?;
	public If_groupElements getIf_groupAccess() {
		return (pIf_group != null) ? pIf_group : (pIf_group = new If_groupElements());
	}
	
	public ParserRule getIf_groupRule() {
		return getIf_groupAccess().getRule();
	}

	//elif_groups:
	//	elif_group+;
	public Elif_groupsElements getElif_groupsAccess() {
		return (pElif_groups != null) ? pElif_groups : (pElif_groups = new Elif_groupsElements());
	}
	
	public ParserRule getElif_groupsRule() {
		return getElif_groupsAccess().getRule();
	}

	//// FUNCTION
	//FunctionDeclaration:
	//	{FunctionDeclaration} type=Type name=ID "(" (params+=Parameter ("," params+=Parameter)*)? ")" "{" escopo=statement?
	//	"}";
	public FunctionDeclarationElements getFunctionDeclarationAccess() {
		return (pFunctionDeclaration != null) ? pFunctionDeclaration : (pFunctionDeclaration = new FunctionDeclarationElements());
	}
	
	public ParserRule getFunctionDeclarationRule() {
		return getFunctionDeclarationAccess().getRule();
	}

	//Parameter:
	//	{Parameter} type=Type name=ID;
	public ParameterElements getParameterAccess() {
		return (pParameter != null) ? pParameter : (pParameter = new ParameterElements());
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}

	//VarDecl:
	//	{VarDecl} type=Type name=ID;
	public VarDeclElements getVarDeclAccess() {
		return (pVarDecl != null) ? pVarDecl : (pVarDecl = new VarDeclElements());
	}
	
	public ParserRule getVarDeclRule() {
		return getVarDeclAccess().getRule();
	}

	//Type:
	//	{Type} sts=simple_type_specifier;
	public TypeElements getTypeAccess() {
		return (pType != null) ? pType : (pType = new TypeElements());
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	//simple_type_specifier:
	//	{IntType} name="int" | {BoolType} name="bool" | {UnknownType} name=ID;
	public Simple_type_specifierElements getSimple_type_specifierAccess() {
		return (pSimple_type_specifier != null) ? pSimple_type_specifier : (pSimple_type_specifier = new Simple_type_specifierElements());
	}
	
	public ParserRule getSimple_type_specifierRule() {
		return getSimple_type_specifierAccess().getRule();
	}

	////// A.5
	////	selection_statement
	//statement: //	expression_statement|
	////	compound_statement|
	////	jump_statement|
	//	{statement} variavel=declaration_statement;
	public StatementElements getStatementAccess() {
		return (pStatement != null) ? pStatement : (pStatement = new StatementElements());
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}

	////iteration_statement:
	////	'while (' condition ')' statement|
	////	'do' statement 'while ('expression ');'|
	////	'for ( 'for_init_statement condition? ';' expression? ')' statement;
	////
	////for_init_statement:
	////	expression_statement|simple_declaration;
	////
	//simple_declaration:
	//	variavel=VarDecl ";";
	public Simple_declarationElements getSimple_declarationAccess() {
		return (pSimple_declaration != null) ? pSimple_declaration : (pSimple_declaration = new Simple_declarationElements());
	}
	
	public ParserRule getSimple_declarationRule() {
		return getSimple_declarationAccess().getRule();
	}

	////expression_statement:
	////	expression?
	////;
	////compound_statement:
	////	'{' statement_seq? '}';
	////	
	////statement_seq:
	////	(statement)+;
	////selection_statement:
	////	'if (' condition ')' statement |
	////	'if (' condition ')' statement |
	////	'switch (' condition ')' statement;
	////
	////
	////// TODO(condition')
	////condition:
	////	expression
	////;
	////jump_statement:
	////	'break;'|
	////	'continue;'|
	////	'return' expression?';'|
	////	'goto' ID';'
	////;
	//declaration_statement:
	//	variaveis+=block_declaration+;
	public Declaration_statementElements getDeclaration_statementAccess() {
		return (pDeclaration_statement != null) ? pDeclaration_statement : (pDeclaration_statement = new Declaration_statementElements());
	}
	
	public ParserRule getDeclaration_statementRule() {
		return getDeclaration_statementAccess().getRule();
	}

	////
	////// TODO
	/// * 	
	//conditional_expression:
	////	logical_or_expression |
	//	logical_or_expression ('?' expression ':' assignment_expression)?;
	//
	//logical_or_expression:
	//	logical_and_expression ('||' logical_and_expression )*;
	//
	//logical_and_expression:
	//	inclusive_or_expression ('&&' inclusive_or_expression)*;
	//
	//inclusive_or_expression:
	//	exclusive_or_expression ('|' exclusive_or_expression)*;
	//
	//exclusive_or_expression:
	//	and_expression ('^' and_expression)*;
	//
	//and_expression:
	//	equality_expression ('&' equality_expression)*;
	//
	//equality_expression:
	//	relational_expression (('==' | '!=') relational_expression)*;
	//
	//relational_expression:
	//	shift_expression (('<' | '>' | '<=' | '>=') shift_expression)*;
	//
	//shift_expression:
	//	additive_expression (('<<' | '>>') additive_expression)*;
	//
	//additive_expression:
	//	multiplicative_expression (SIGN multiplicative_expression)*;
	//
	//multiplicative_expression:
	//	pm_expression (('*' | '/' | '%') pm_expression)*;
	//
	//pm_expression:
	//	cast_expression (('.*' | '->*') cast_expression)*;
	//
	//cast_expression:
	//	('(' ID ')')* unary_expression;
	//	//TODO replace ID with type_id, I guess
	//
	//unary_expression:
	//	('sizeof')* postfix_expression |
	//	('sizeof')* ('++' | '--' | unary_operator ) cast_expression |
	//	'sizeof' '(' ID ')' |//TODO replace ID with type_id
	//	('sizeof')* new_expression |
	//	('sizeof')* delete_expression;
	//
	//postfix_expression:
	//	primary_expression ('[' expression ']' |
	//						'(' expression_list? ')' |
	//						'.' 'template'? (ID) | //TODO replace ID with id_expression
	//						'->' 'template'? (ID) | //TODO replace ID with id_expression
	//						'++' |
	//						'--')*;
	//
	//primary_expression:
	//	'==primary==';
	//
	//pseudo_destructor_name:
	//	'::'? nested_name_specifier? type_name '::' '~' type_name |
	//	'::'? nested_name_specifier => 'template' template_id '::' '~' type_name;
	//
	//nested_name_specifier:
	//	class_or_namespace_name '::' nested_name_specifier?;
	////	class_or_namespace_name '::' => 'template' nested_name_specifier;
	//	
	//
	//class_or_namespace_name:
	//	class_name | namespace_name;
	//
	//class_name:
	//	ID | template_id;
	//
	//namespace_name:
	//	'==namespace==';
	//
	//type_name:
	//	'==type_name==';
	//
	//template_id:
	//	ID '<' template_argument_list? '>' 'class';
	//
	//template_argument_list:
	//	template_argument (',' template_argument)*;
	//
	//template_argument:
	//	assignment_expression |
	//	id_expression;
	//
	//id_expression:
	//	unqualified_id |
	//	qualified_id;
	//
	//unqualified_id:
	//	ID |
	//	operator_function_id |
	//	conversion_function_id |
	//	'~' class_name |
	//	template_id;
	//
	//operator_function_id:
	//	'operator' operator;
	//
	//operator:
	//	'new' | 'delete' | 'new[]' | 'delete[]' | '+' | '-' | '*' | '/' | '%' | '^' | '&' | '|' | '~' | '!' | '=' | '<' | '>' |
	//	'+=' | '-=' | '*=' | '/=' | '%=' | '^=' | '&=' | '|=' | '<<' | '>>' | '<<=' | '>>=' | '==' | '!=' | '<=' | '>=' | '&&' |
	//	'||' | '++' | '--' | ',' | '->*' | '->' | '()' | '[]';
	//
	//conversion_function_id:
	//	'operator' conversion_type_id;
	//
	//conversion_type_id:
	//	type_specifier_seq conversion_declarator?;
	//
	//conversion_declarator:
	//	'==conversion==';
	//
	//type_specifier_seq:
	//	type_specifier+;
	//
	//type_specifier:
	//	'==type_specifier==';
	//
	//qualified_id:
	//	'==qualified==';
	//
	//new_expression:
	//	'==new==';
	//
	//delete_expression:
	//	'==delete==';
	//
	//unary_operator:
	//	('*' | '&' | '+' | '-' | '!' | '~');
	//
	//expression_list:
	//	assignment_expression (',' assignment_expression)*;
	//
	//expression:
	//	'==expression==';
	//
	//assignment_expression:
	//	'==assignment==';
	//
	// * / block_declaration:
	//	{block_declaration} variavel=simple_declaration;
	public Block_declarationElements getBlock_declarationAccess() {
		return (pBlock_declaration != null) ? pBlock_declaration : (pBlock_declaration = new Block_declarationElements());
	}
	
	public ParserRule getBlock_declarationRule() {
		return getBlock_declarationAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
