/*
* generated by Xtext
*/
package org;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class Cpp2UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.ui.internal.Cpp2Activator.getInstance().getInjector("org.Cpp2");
	}
	
}
