/*
* generated by Xtext
*/
package org.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.services.Cpp2GrammarAccess;

public class Cpp2Parser extends AbstractContentAssistParser {
	
	@Inject
	private Cpp2GrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.ui.contentassist.antlr.internal.InternalCpp2Parser createParser() {
		org.ui.contentassist.antlr.internal.InternalCpp2Parser result = new org.ui.contentassist.antlr.internal.InternalCpp2Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPreProcessingTokenAccess().getAlternatives(), "rule__PreProcessingToken__Alternatives");
					put(grammarAccess.getPreProcessingTokenAccess().getAlternatives_2_0(), "rule__PreProcessingToken__Alternatives_2_0");
					put(grammarAccess.getPreProcessingTokenAccess().getAlternatives_2_1(), "rule__PreProcessingToken__Alternatives_2_1");
					put(grammarAccess.getPreProcessingTokenAccess().getAlternatives_2_1_2_0(), "rule__PreProcessingToken__Alternatives_2_1_2_0");
					put(grammarAccess.getPreProcessingTokenAccess().getAlternatives_2_1_2_1(), "rule__PreProcessingToken__Alternatives_2_1_2_1");
					put(grammarAccess.getTokenAccess().getAlternatives(), "rule__Token__Alternatives");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getLiteralAccess().getAlternatives_4_0(), "rule__Literal__Alternatives_4_0");
					put(grammarAccess.getOverloadableOperatorAccess().getAlternatives(), "rule__OverloadableOperator__Alternatives");
					put(grammarAccess.getTemplateParameterAccess().getAlternatives(), "rule__TemplateParameter__Alternatives");
					put(grammarAccess.getTypeParameterAccess().getAlternatives(), "rule__TypeParameter__Alternatives");
					put(grammarAccess.getTypeParameterAccess().getAlternatives_0_1(), "rule__TypeParameter__Alternatives_0_1");
					put(grammarAccess.getTypeParameterAccess().getAlternatives_1_1(), "rule__TypeParameter__Alternatives_1_1");
					put(grammarAccess.getTypeParameterAccess().getAlternatives_2_5(), "rule__TypeParameter__Alternatives_2_5");
					put(grammarAccess.getTemplateIdAccess().getAlternatives(), "rule__TemplateId__Alternatives");
					put(grammarAccess.getTemplateArgumentAccess().getAlternatives(), "rule__TemplateArgument__Alternatives");
					put(grammarAccess.getTypenameSpecifierAccess().getAlternatives_3(), "rule__TypenameSpecifier__Alternatives_3");
					put(grammarAccess.getPreProcessingTokenAccess().getGroup_2(), "rule__PreProcessingToken__Group_2__0");
					put(grammarAccess.getPreProcessingTokenAccess().getGroup_2_0_1(), "rule__PreProcessingToken__Group_2_0_1__0");
					put(grammarAccess.getPreProcessingTokenAccess().getGroup_2_1_2(), "rule__PreProcessingToken__Group_2_1_2__0");
					put(grammarAccess.getTokenAccess().getGroup_2(), "rule__Token__Group_2__0");
					put(grammarAccess.getLiteralAccess().getGroup_4(), "rule__Literal__Group_4__0");
					put(grammarAccess.getOperatorFunctionIdAccess().getGroup(), "rule__OperatorFunctionId__Group__0");
					put(grammarAccess.getOperatorFunctionIdAccess().getGroup_2(), "rule__OperatorFunctionId__Group_2__0");
					put(grammarAccess.getOverloadableOperatorAccess().getGroup_2(), "rule__OverloadableOperator__Group_2__0");
					put(grammarAccess.getOverloadableOperatorAccess().getGroup_3(), "rule__OverloadableOperator__Group_3__0");
					put(grammarAccess.getLiteralOperatorIdAccess().getGroup(), "rule__LiteralOperatorId__Group__0");
					put(grammarAccess.getTemplateDeclarationAccess().getGroup(), "rule__TemplateDeclaration__Group__0");
					put(grammarAccess.getTemplateParameterListAccess().getGroup(), "rule__TemplateParameterList__Group__0");
					put(grammarAccess.getTemplateParameterListAccess().getGroup_1(), "rule__TemplateParameterList__Group_1__0");
					put(grammarAccess.getTypeParameterAccess().getGroup_0(), "rule__TypeParameter__Group_0__0");
					put(grammarAccess.getTypeParameterAccess().getGroup_0_1_0(), "rule__TypeParameter__Group_0_1_0__0");
					put(grammarAccess.getTypeParameterAccess().getGroup_0_1_1(), "rule__TypeParameter__Group_0_1_1__0");
					put(grammarAccess.getTypeParameterAccess().getGroup_1(), "rule__TypeParameter__Group_1__0");
					put(grammarAccess.getTypeParameterAccess().getGroup_1_1_0(), "rule__TypeParameter__Group_1_1_0__0");
					put(grammarAccess.getTypeParameterAccess().getGroup_1_1_1(), "rule__TypeParameter__Group_1_1_1__0");
					put(grammarAccess.getTypeParameterAccess().getGroup_2(), "rule__TypeParameter__Group_2__0");
					put(grammarAccess.getTypeParameterAccess().getGroup_2_5_0(), "rule__TypeParameter__Group_2_5_0__0");
					put(grammarAccess.getTypeParameterAccess().getGroup_2_5_1(), "rule__TypeParameter__Group_2_5_1__0");
					put(grammarAccess.getSimpleTemplateIdAccess().getGroup(), "rule__SimpleTemplateId__Group__0");
					put(grammarAccess.getTemplateIdAccess().getGroup_1(), "rule__TemplateId__Group_1__0");
					put(grammarAccess.getTemplateIdAccess().getGroup_2(), "rule__TemplateId__Group_2__0");
					put(grammarAccess.getTemplateArgumentListAccess().getGroup(), "rule__TemplateArgumentList__Group__0");
					put(grammarAccess.getTemplateArgumentListAccess().getGroup_2(), "rule__TemplateArgumentList__Group_2__0");
					put(grammarAccess.getTypenameSpecifierAccess().getGroup(), "rule__TypenameSpecifier__Group__0");
					put(grammarAccess.getTypenameSpecifierAccess().getGroup_3_1(), "rule__TypenameSpecifier__Group_3_1__0");
					put(grammarAccess.getExplicitInstantiationAccess().getGroup(), "rule__ExplicitInstantiation__Group__0");
					put(grammarAccess.getExplicitSpecializationAccess().getGroup(), "rule__ExplicitSpecialization__Group__0");
					put(grammarAccess.getTestAccess().getElementsAssignment(), "rule__Test__ElementsAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.ui.contentassist.antlr.internal.InternalCpp2Parser typedParser = (org.ui.contentassist.antlr.internal.InternalCpp2Parser) parser;
			typedParser.entryRuleTest();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public Cpp2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Cpp2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
